version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ora
    versions:
    - 5.2.0
    - 5.3.0
  - dependency-name: qunit
    versions:
    - 2.13.0
    - 2.14.0
  - dependency-name: testem
    versions:
    - 3.2.0
